import { AudioEventSink, ScheduledEvent } from '@precision-loop/audio-scheduler';
import { PlaybackEngine } from '@precision-loop/playback-engine';
import { LOOP_ITERATION_EVENT_TYPE } from '@precision-loop/playback-engine';

export class ApplicationEventRouter implements AudioEventSink {
    public playbackEngine?: PlaybackEngine;
    
    schedule(event: ScheduledEvent): void {
        // Forward looping events to the playback engine if it's connected
        if (event.type === LOOP_ITERATION_EVENT_TYPE && this.playbackEngine) {
            this.playbackEngine.schedule(event);
        }
        // CLICK events generated by Transport can safely be ignored/routed here
        // without breaking playback, because they are dispatched into the generic
        // sink but the Transport schedules them with type 'CLICK'. Since this
        // sink drops them, it implies clicking is handled externally if needed,
        // or we can add a metronome synth here later.
    }
}
