import { AudioEventSink, ScheduledEvent } from '@precision-loop/audio-scheduler';
import { PlaybackEngine } from '@precision-loop/playback-engine';
import { LOOP_ITERATION_EVENT_TYPE } from '@precision-loop/playback-engine';

export class ApplicationEventRouter implements AudioEventSink {
    public playbackEngine?: PlaybackEngine;
    private context?: AudioContext;

    public setAudioContext(context: AudioContext): void {
        this.context = context;
    }
    
    schedule(event: ScheduledEvent): void {
        // Forward looping events to the playback engine if it's connected
        if (event.type === LOOP_ITERATION_EVENT_TYPE && this.playbackEngine) {
            this.playbackEngine.schedule(event);
        }
        
        // CLICK events generated by Transport
        if (event.type === 'CLICK' && this.context) {
            this.playClick(event.time, (event.payload as any).accent);
        }
    }

    private playClick(time: number, isAccent: boolean): void {
        if (!this.context) return;
        
        const osc = this.context.createOscillator();
        const gain = this.context.createGain();
        
        osc.connect(gain);
        gain.connect(this.context.destination);
        
        // Settings for metronome click
        osc.type = 'sine';
        osc.frequency.setValueAtTime(isAccent ? 1200 : 800, time);
        
        // Short snappy envelope
        gain.gain.setValueAtTime(0, time);
        gain.gain.linearRampToValueAtTime(0.5, time + 0.005);
        gain.gain.exponentialRampToValueAtTime(0.001, time + 0.1);
        
        osc.start(time);
        osc.stop(time + 0.1);
    }
}
